version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    msbuild PopCom\PopCom.csproj

    msbuild PopComSetup\PopComSetup.wixproj
artifacts:
- path: PopComSetup\bin\Release\en-us\PopComSetup.msi
  name: PopComSetup